[package]
name = "two_int_prblm_1409a"
version = "0.1.0"
authors = ["Aryan-dev007 <aryansinha6363@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
