[package]
name = "pub_fn_use"
version = "0.1.0"
authors = ["aa-ryan <aryansinha6363@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_mod
